import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

export default defineSchema({
  ...authTables,
  users: defineTable({
    email: v.string(), name: v.string(),
    role: v.optional(v.union(v.literal("admin"), v.literal("organizer"), v.literal("judge"), v.literal("participant"))),
    bio: v.optional(v.string()), avatarUrl: v.optional(v.string()), tokenIdentifier: v.optional(v.string()),
    totpSecret: v.optional(v.string()), totpEnabled: v.optional(v.boolean()), totpEnrolledAt: v.optional(v.number()),
    totpLastVerifiedAt: v.optional(v.number()), emailVerificationTime: v.optional(v.number()),
    disabledAt: v.optional(v.number()), disabled_at: v.optional(v.number()),
  }).index("by_token", ["tokenIdentifier"]).index("by_role", ["role"]).index("email", ["email"]),
  events: defineTable({
    slug: v.string(), title: v.string(), tagline: v.string(), description: v.string(), status: v.string(),
    registrationStart: v.number(), registrationEnd: v.number(), submissionDeadline: v.number(),
    judgingStart: v.number(), judgingEnd: v.number(), votingStart: v.number(), votingEnd: v.number(),
    timezone: v.string(), settings: v.string(), bannerUrl: v.optional(v.string()),
    organizerId: v.optional(v.id("users")), hostName: v.optional(v.string()), shortDescription: v.optional(v.string()),
    fullDescription: v.optional(v.string()), rules: v.optional(v.string()), registrationOpens: v.optional(v.number()),
    registrationCloses: v.optional(v.number()), submissionOpens: v.optional(v.number()), judgingStarts: v.optional(v.number()),
    judgingEnds: v.optional(v.number()), resultsAnnounced: v.optional(v.number()), minTeamSize: v.optional(v.number()),
    maxTeamSize: v.optional(v.number()), soloAllowed: v.optional(v.boolean()), coverImageRequired: v.optional(v.boolean()),
    publishedAt: v.optional(v.number()),
    // Winner override (T2 results): the project pinned to #1, and whether #1
    // came from an override rather than the computed ranking.
    winnerOverrideProjectId: v.optional(v.id("submissions")),
    winnerIsOverridden: v.optional(v.boolean()),
  }).index("by_slug", ["slug"]).index("by_organizer", ["organizerId"]),
  tracks: defineTable({ eventId: v.id("events"), name: v.string(), description: v.string(), prizeDescription: v.string(), prizeAmount: v.number() }).index("by_event", ["eventId"]),
  teams: defineTable({ eventId: v.id("events"), name: v.string(), inviteCode: v.string(), trackId: v.optional(v.id("tracks")), createdBy: v.id("users") }).index("by_event", ["eventId"]).index("by_invite", ["inviteCode"]),
  teamMembers: defineTable({ teamId: v.id("teams"), userId: v.id("users"), memberRole: v.string(), joinedAt: v.number() }).index("by_team", ["teamId"]).index("by_user", ["userId"]),
  submissions: defineTable({ eventId: v.id("events"), teamId: v.id("teams"), trackId: v.optional(v.id("tracks")), title: v.string(), tagline: v.string(), description: v.string(), repositoryUrl: v.string(), videoUrl: v.string(), demoUrl: v.string(), tags: v.string(), customFields: v.string(), status: v.string(), submittedAt: v.optional(v.number()), updatedAt: v.number() }).index("by_event", ["eventId"]).index("by_team", ["teamId"]),
  rubricCriteria: defineTable({ eventId: v.id("events"), name: v.string(), description: v.string(), weight: v.number(), minScore: v.number(), maxScore: v.number(), sortOrder: v.number() }).index("by_event", ["eventId"]),
  judgeAssignments: defineTable({ eventId: v.id("events"), judgeId: v.id("users"), submissionId: v.id("submissions"), status: v.string(), assignedAt: v.number(), completedAt: v.optional(v.number()) }).index("by_event", ["eventId"]).index("by_judge", ["judgeId"]).index("by_submission", ["submissionId"]),
  judgeScores: defineTable({ eventId: v.id("events"), assignmentId: v.id("judgeAssignments"), submissionId: v.id("submissions"), judgeId: v.id("users"), criterionId: v.id("rubricCriteria"), score: v.number(), privateNotes: v.string(), submittedAt: v.number() }).index("by_assignment", ["assignmentId"]).index("by_event", ["eventId"]).index("by_judge_submission", ["judgeId", "submissionId"]),
  pairwiseMatches: defineTable({ eventId: v.id("events"), judgeId: v.id("users"), submissionAId: v.id("submissions"), submissionBId: v.id("submissions"), winnerId: v.string(), createdAt: v.number() }).index("by_event", ["eventId"]),
  communityVotes: defineTable({ eventId: v.id("events"), userId: v.id("users"), submissionId: v.id("submissions"), points: v.number(), creditsSpent: v.number(), ipHash: v.string(), userAgentHash: v.string(), createdAt: v.number() }).index("by_event", ["eventId"]).index("by_user_event", ["userId", "eventId"]).index("by_submission", ["submissionId"]),
  comments: defineTable({ submissionId: v.id("submissions"), userId: v.id("users"), content: v.string(), isFlagged: v.boolean(), createdAt: v.number() }).index("by_submission", ["submissionId"]),
  auditLogs: defineTable({ eventId: v.optional(v.id("events")), actorId: v.optional(v.id("users")), action: v.string(), targetType: v.string(), targetId: v.string(), beforeState: v.string(), afterState: v.string(), ipAddress: v.string(), prevHash: v.string(), entryHash: v.string(), timestamp: v.number() }).index("by_event", ["eventId"]).index("by_action", ["action"]),
  webhooks: defineTable({ eventId: v.id("events"), targetUrl: v.string(), secretKey: v.string(), events: v.string(), isActive: v.boolean(), createdAt: v.number() }).index("by_event", ["eventId"]),
  webhookDeliveries: defineTable({ webhookId: v.id("webhooks"), eventType: v.string(), payload: v.string(), statusCode: v.number(), success: v.boolean(), deliveredAt: v.number() }).index("by_webhook", ["webhookId"]),
  certificates: defineTable({ certUuid: v.string(), eventId: v.id("events"), userId: v.id("users"), recipientName: v.string(), certType: v.string(), title: v.string(), trackName: v.string(), rank: v.number(), signatureHash: v.string(), issuedAt: v.number() }).index("by_uuid", ["certUuid"]).index("by_event", ["eventId"]),
  platform: defineTable({ key: v.string(), value: v.string() }).index("by_key", ["key"]),
  invites: defineTable({
    email: v.optional(v.string()),
    role: v.string(),
    eventId: v.optional(v.id("events")),
    tokenHash: v.string(),
    createdBy: v.id("users"),
    createdAt: v.number(),
    expiresAt: v.number(),
    usedAt: v.optional(v.number()),
    revokedAt: v.optional(v.number()),
  }).index("by_token_hash", ["tokenHash"]).index("by_email", ["email"]),
  event_participants: defineTable({
    eventId: v.id("events"),
    userId: v.id("users"),
    status: v.string(),
    lookingForTeam: v.optional(v.boolean()),
    createdAt: v.number(),
  }).index("by_event", ["eventId"]).index("by_user", ["userId"]).index("by_event_user", ["eventId", "userId"]),
  flags: defineTable({
    submissionId: v.id("submissions"),
    eventId: v.id("events"),
    reason: v.string(),
    /** "duplicate" (same team) or "review" (cross-team repo, plagiarism hint). */
    severity: v.optional(v.string()),
    status: v.string(),
    createdAt: v.number(),
    reviewedAt: v.optional(v.number()),
  }).index("by_submission", ["submissionId"]).index("by_event", ["eventId"]),
  winnerOverrides: defineTable({
    eventId: v.id("events"),
    requestedBy: v.id("users"),
    requestedAt: v.number(),
    targetProjectId: v.id("submissions"),
    reason: v.string(),
    status: v.union(v.literal("pending"), v.literal("accepted"), v.literal("rejected")),
    /** "organizer_request" (needs admin approval) or "admin_direct". */
    source: v.optional(v.string()),
    reviewedBy: v.optional(v.id("users")),
    reviewedAt: v.optional(v.number()),
    reviewerNote: v.optional(v.string()),
    appliedAt: v.optional(v.number()),
  }).index("by_event", ["eventId"]).index("by_status", ["status"]).index("by_target", ["targetProjectId"]),
  teamMessages: defineTable({
    teamId: v.id("teams"),
    userId: v.id("users"),
    content: v.string(),
    fileStorageId: v.optional(v.id("_storage")),
    fileName: v.optional(v.string()),
    fileType: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_team", ["teamId"]),
});
