import { Link, NavLink, Outlet, useNavigate } from "react-router-dom";
import { useQuery, useConvexAuth } from "convex/react";
import { useAuthActions } from "@convex-dev/auth/react";
import { api } from "../../convex/_generated/api";
import { Menu, X, LogOut, Sparkles, UserRound } from "lucide-react";
import { useState } from "react";

export default function AppShell(){ const {isAuthenticated}=useConvexAuth(); const me=useQuery(api.users.me,{}); const {signOut}=useAuthActions(); const navigate=useNavigate(); const [menu,setMenu]=useState(false);
 const links=me?.role==="organizer"?[["Overview","/organizer"],["Events","/organizer/events"]]:me?.role==="judge"?[["Queue","/judge"]]:me?.role==="admin"?[["Overview","/admin"],["Events","/organizer/events"]]:[["Discover","/dashboard"],["Workspace","/workspace"],["Browse","/e/dogfood-2026"]];
 async function logout(){await signOut();navigate("/");}
 return <div className="min-h-screen"><header className="sticky top-0 z-50 border-b border-white/70 bg-white/55 backdrop-blur-2xl"><div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-5 px-5 lg:px-8"><Link to="/" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-2xl border border-white/80 bg-white/70 shadow-sm"><Sparkles size={16}/></span><span className="text-lg font-bold tracking-tight">RaptorJudge</span></Link><nav className="hidden items-center gap-7 md:flex">{links.map(([label,href])=><NavLink key={href} to={href} className={({isActive})=>`text-sm transition ${isActive?"font-semibold":"text-muted-foreground hover:text-foreground"}`}>{label}</NavLink>)}</nav><div className="flex items-center gap-2">{isAuthenticated&&me?<><Link to="/security" className="glass-button hidden h-10 px-3 sm:inline-flex"><UserRound size={15}/>{me.name}</Link><button onClick={logout} aria-label="Log out" className="glass-button hidden h-10 w-10 p-0 sm:inline-flex"><LogOut size={15}/></button></>:<Link to="/auth" className="glass-button hidden h-10 sm:inline-flex">Sign in</Link>}<button aria-label="Open navigation" onClick={()=>setMenu(v=>!v)} className="glass-button h-10 w-10 p-0 md:hidden">{menu?<X size={17}/>:<Menu size={17}/>}</button></div></div>{menu&&<nav className="mx-auto grid max-w-7xl gap-1 border-t border-border/60 px-5 py-3 md:hidden">{links.map(([label,href])=><Link key={href} onClick={()=>setMenu(false)} to={href} className="rounded-2xl px-3 py-3 text-sm hover:bg-white/70">{label}</Link>)}{isAuthenticated&&<><Link to="/security" onClick={()=>setMenu(false)} className="rounded-2xl px-3 py-3 text-sm">Account</Link><button onClick={logout} className="px-3 py-3 text-left text-sm text-muted-foreground">Log out</button></>}</nav>}</header><main><Outlet/></main><footer className="mx-auto mt-16 flex max-w-7xl flex-col gap-2 border-t border-border/60 px-5 py-8 text-sm text-muted-foreground sm:flex-row sm:justify-between lg:px-8"><span>RaptorJudge</span><span>Clear tools for better judging.</span></footer></div>; }
