import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import { api } from "@/convex/_generated/api";

const fieldClass = "w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-ring";
const slugify = (s: string) => s.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const toTs = (s: string, optional = false) => optional && !s ? undefined : new Date(s).getTime();
const fromTs = (n?: number) => n ? new Date(n).toISOString().slice(0, 16) : "";

type Form = { title:string; slug:string; hostName:string; bannerUrl:string; shortDescription:string; fullDescription:string; rules:string; registrationOpens:string; registrationCloses:string; submissionOpens:string; submissionDeadline:string; judgingStarts:string; judgingEnds:string; resultsAnnounced:string; minTeamSize:number; maxTeamSize:number; soloAllowed:boolean; coverImageRequired:boolean };
const blank: Form = { title:"", slug:"", hostName:"", bannerUrl:"", shortDescription:"", fullDescription:"", rules:"", registrationOpens:"", registrationCloses:"", submissionOpens:"", submissionDeadline:"", judgingStarts:"", judgingEnds:"", resultsAnnounced:"", minTeamSize:1, maxTeamSize:4, soloAllowed:true, coverImageRequired:false };

export default function EventForm({ edit = false }: { edit?: boolean }) {
  const { slug } = useParams(); const navigate = useNavigate();
  const event = useQuery(api.events.getBySlug, edit && slug ? { slug } : "skip");
  const create = useMutation(api.events.create); const update = useMutation(api.events.update); const remove = useMutation(api.events.deleteEvent);
  const [form, setForm] = useState<Form>(blank); const [slugLocked, setSlugLocked] = useState(!edit); const [preview, setPreview] = useState<"fullDescription"|"rules">("fullDescription"); const [busy, setBusy] = useState(false);
  useEffect(() => { if (event) setForm({ title:event.title, slug:event.slug, hostName:event.hostName ?? "", bannerUrl:event.bannerUrl ?? "", shortDescription:event.shortDescription ?? event.tagline, fullDescription:event.fullDescription ?? event.description, rules:event.rules ?? "", registrationOpens:fromTs(event.registrationOpens ?? event.registrationStart), registrationCloses:fromTs(event.registrationCloses ?? event.registrationEnd), submissionOpens:fromTs(event.submissionOpens), submissionDeadline:fromTs(event.submissionDeadline), judgingStarts:fromTs(event.judgingStarts ?? event.judgingStart), judgingEnds:fromTs(event.judgingEnds ?? event.judgingEnd), resultsAnnounced:fromTs(event.resultsAnnounced ?? event.votingEnd), minTeamSize:event.minTeamSize ?? 1, maxTeamSize:event.maxTeamSize ?? 4, soloAllowed:event.soloAllowed ?? true, coverImageRequired:event.coverImageRequired ?? false }); }, [event]);
  const set = (key: keyof Form, value: any) => setForm((f) => ({ ...f, [key]: value }));
  const payload = useMemo(() => ({ slug:form.slug, title:form.title, tagline:form.shortDescription, description:form.fullDescription, registrationStart:toTs(form.registrationOpens, true) ?? Date.now(), registrationEnd:toTs(form.registrationCloses) ?? Date.now(), submissionDeadline:toTs(form.submissionDeadline) ?? Date.now(), judgingStart:toTs(form.judgingStarts, true) ?? Date.now(), judgingEnd:toTs(form.judgingEnds, true) ?? Date.now(), votingStart:toTs(form.resultsAnnounced, true) ?? Date.now(), votingEnd:toTs(form.resultsAnnounced) ?? Date.now(), timezone:Intl.DateTimeFormat().resolvedOptions().timeZone, bannerUrl:form.bannerUrl || undefined, hostName:form.hostName || undefined, shortDescription:form.shortDescription, fullDescription:form.fullDescription, rules:form.rules, registrationOpens:toTs(form.registrationOpens, true), registrationCloses:toTs(form.registrationCloses), submissionOpens:toTs(form.submissionOpens, true), judgingStarts:toTs(form.judgingStarts, true), judgingEnds:toTs(form.judgingEnds, true), resultsAnnounced:toTs(form.resultsAnnounced), minTeamSize:Number(form.minTeamSize), maxTeamSize:Number(form.maxTeamSize), soloAllowed:form.soloAllowed, coverImageRequired:form.coverImageRequired }), [form]);
  async function save() { if (!form.title.trim() || !form.slug.trim() || !form.registrationCloses || !form.submissionDeadline || !form.resultsAnnounced) { toast.error("Complete all required fields"); return; } setBusy(true); try { if (edit && event) await update({ eventId:event._id, ...payload }); else await create(payload); toast.success(edit ? "Event updated" : "Draft saved"); navigate(`/organizer/events/${form.slug}`); } catch (e:any) { toast.error(e.message); } finally { setBusy(false); } }
  return <div className="container max-w-5xl py-8"><div className="mb-8"><div className="mono-label mb-1">{edit ? "edit event" : "new event"}</div><h1 className="text-3xl font-bold">{edit ? form.title || "Edit event" : "Create an event"}</h1><p className="mt-2 text-sm text-muted-foreground">Build a self-hosted hackathon event. Fields marked * are required.</p></div>
    <div className="grid gap-6"><section className="rounded-xl border border-border bg-card p-6"><h2 className="mb-4 text-lg font-semibold">Identity</h2><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1"><span className="mono-label">Title *</span><input autoFocus className={fieldClass} value={form.title} onChange={e=>{set("title",e.target.value); if(!edit || slugLocked) set("slug",slugify(e.target.value));}} /></label><label className="grid gap-1"><span className="mono-label">Slug *</span><input className={fieldClass} value={form.slug} onChange={e=>{setSlugLocked(false);set("slug",slugify(e.target.value));}} /></label><label className="grid gap-1"><span className="mono-label">Host / organizer name</span><input className={fieldClass} value={form.hostName} onChange={e=>set("hostName",e.target.value)} /></label><label className="grid gap-1"><span className="mono-label">Banner image URL (self-hosted)</span><input className={fieldClass} placeholder="/uploads/events/banner.webp" value={form.bannerUrl} onChange={e=>set("bannerUrl",e.target.value)} /></label></div><label className="mt-4 grid gap-1"><span className="mono-label">Short description ({form.shortDescription.length}/280)</span><textarea maxLength={280} rows={2} className={fieldClass} value={form.shortDescription} onChange={e=>set("shortDescription",e.target.value)} /></label></section>
    <MarkdownField label="Full description" value={form.fullDescription} onChange={v=>set("fullDescription",v)} active={preview === "fullDescription"} onPreview={()=>setPreview("fullDescription")} required /><MarkdownField label="Rules" value={form.rules} onChange={v=>set("rules",v)} active={preview === "rules"} onPreview={()=>setPreview("rules")} />
    <section className="rounded-xl border border-border bg-card p-6"><h2 className="mb-4 text-lg font-semibold">Schedule</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{([ ["registrationOpens","Registration opens"],["registrationCloses","Registration closes *"],["submissionOpens","Submission opens"],["submissionDeadline","Submission deadline *"],["judgingStarts","Judging starts"],["judgingEnds","Judging ends"],["resultsAnnounced","Results announced *"]] as [keyof Form,string][]).map(([key,label])=><label key={key} className="grid gap-1"><span className="mono-label">{label}</span><input type="datetime-local" className={fieldClass} value={form[key] as string} onChange={e=>set(key,e.target.value)} /></label>)}</div></section>
    <section className="rounded-xl border border-border bg-card p-6"><h2 className="mb-4 text-lg font-semibold">Participation settings</h2><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1"><span className="mono-label">Minimum team size</span><input type="number" min={1} className={fieldClass} value={form.minTeamSize} onChange={e=>set("minTeamSize",Number(e.target.value))} /></label><label className="grid gap-1"><span className="mono-label">Maximum team size</span><input type="number" min={1} className={fieldClass} value={form.maxTeamSize} onChange={e=>set("maxTeamSize",Number(e.target.value))} /></label></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Toggle label="Solo participation allowed" checked={form.soloAllowed} onChange={v=>set("soloAllowed",v)} /><Toggle label="Cover image required for submissions" checked={form.coverImageRequired} onChange={v=>set("coverImageRequired",v)} /></div></section>
    <div className="flex flex-wrap justify-between gap-3"><button onClick={()=>navigate("/organizer")} className="rounded-lg border border-border px-4 py-2.5 font-mono text-xs uppercase">Cancel</button><div className="flex gap-2">{edit && event?.status === "draft" && <button onClick={async()=>{if(confirm("Delete this draft event?")){await remove({eventId:event._id});navigate("/organizer/events");}}} className="rounded-lg border border-destructive/40 px-4 py-2.5 font-mono text-xs uppercase text-destructive">Delete</button>}<button disabled={busy} onClick={save} className="rounded-lg bg-primary px-5 py-2.5 font-mono text-xs font-semibold uppercase text-primary-foreground disabled:opacity-50">{busy ? "Saving…" : "Save as draft"}</button></div></div></div>
  </div>;
}
function MarkdownField({label,value,onChange,active,onPreview,required}:{label:string;value:string;onChange:(v:string)=>void;active:boolean;onPreview:()=>void;required?:boolean}) { return <section className="rounded-xl border border-border bg-card p-6"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">{label}{required ? " *" : ""}</h2><button type="button" onClick={onPreview} className="font-mono text-xs uppercase text-primary">{active ? "preview" : "edit"}</button></div>{active ? <div className="min-h-28 whitespace-pre-wrap rounded-lg bg-secondary/40 p-4 text-sm leading-relaxed">{value || "Nothing to preview yet."}</div> : <textarea rows={7} className={`${fieldClass} font-mono`} value={value} onChange={e=>onChange(e.target.value)} placeholder={`Write ${label.toLowerCase()} in markdown…`} />}</section> }
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}) { return <label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="h-4 w-4 accent-[hsl(var(--primary))]" />{label}</label> }
