import { useQuery } from "convex/react";
import { Link } from "react-router-dom";
import { api } from "@/convex/_generated/api";
import { Gavel, CheckCircle2, Circle, ArrowRight } from "lucide-react";

export default function JudgePortal() {
  const event = useQuery(api.events.getBySlug, { slug: "dogfood-2026" });
  const queue = useQuery(api.judging.myQueue, event ? { eventId: event._id } : "skip");
  if (!event || !queue) return <div className="container py-24 text-center font-mono text-muted-foreground">loading…</div>;
  const completed = queue.items.filter((i: any) => i.status === "completed").length; const total = queue.items.length; const percent = total ? Math.round((completed / total) * 100) : 0;
  return <div className="container max-w-4xl py-10"><header className="mb-8"><div className="mono-label mb-1">judge portal</div><h1 className="flex items-center gap-3 text-3xl font-bold tracking-tight"><Gavel className="text-primary" size={28} />Judge Portal</h1><div className="mt-4 flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${percent}%` }} /></div><span className="whitespace-nowrap font-mono text-xs text-muted-foreground">You&apos;ve scored {completed} of {total}</span></div>{!queue.judgingOpen && <p className="mt-3 rounded-lg border border-accent/40 bg-accent/10 px-4 py-2 font-mono text-xs">Judging is not open yet — stage: {event.status}</p>}</header><section><div className="mb-3"><h2 className="text-lg font-semibold">Assigned queue</h2><p className="mt-1 text-sm text-muted-foreground">Open one project at a time and submit your rubric scores.</p></div><div className="grid gap-3">{queue.items.map((item: any) => <div key={item.assignmentId} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-border bg-card p-5"><div className="flex items-center gap-3"><span>{item.status === "completed" ? <CheckCircle2 className="text-success" size={20} /> : <Circle className="text-muted-foreground" size={20} />}</span><div><h3 className="font-semibold">{item.submission.title}</h3><p className="font-mono text-xs text-muted-foreground">{item.submission.teamName} · {item.status === "completed" ? "Scored" : "Needs score"}</p></div></div><Link to={`/judge/score/${item.assignmentId}`} className="min-h-11 inline-flex items-center gap-2 rounded-lg bg-primary px-4 font-mono text-xs font-semibold uppercase text-primary-foreground">Score <ArrowRight size={14} /></Link></div>)}{queue.items.length === 0 && <div className="rounded-xl border border-dashed border-border bg-card/50 p-10 text-center text-sm text-muted-foreground">No assignments yet. Ask an organizer to run the assignment engine.</div>}</div></section></div>;
}
