import { useQuery, useMutation } from "convex/react";
import { Link, useParams, Navigate } from "react-router-dom";
import { useMemo, useState } from "react";
import { api } from "@/convex/_generated/api";
import { toast } from "sonner";

export default function JudgeScore() {
  const { id } = useParams(); const event = useQuery(api.events.getBySlug, { slug: "dogfood-2026" }); const queue = useQuery(api.judging.myQueue, event ? { eventId: event._id } : "skip"); const rubric = useQuery(api.judging.rubricForEvent, event ? { eventId: event._id } : "skip"); const submit = useMutation(api.judging.submitScores);
  const item = queue?.items.find((candidate: any) => String(candidate.assignmentId) === String(id));
  const [notes, setNotes] = useState(""); const [busy, setBusy] = useState(false); const sorted = useMemo(() => [...(rubric ?? [])].sort((a: any, b: any) => a.sortOrder - b.sortOrder), [rubric]); const [scores, setScores] = useState<Record<string, number>>({});
  if (!event || !queue || !rubric) return <div className="container py-24 text-center font-mono text-muted-foreground">loading…</div>;
  if (!item) return <Navigate to="/judge" replace />;
  const selectedItem = item;
  const allScored = sorted.every((c: any) => scores[c._id] !== undefined || selectedItem.scoredCriteria.some((s: any) => s.criterionId === c._id));
  async function save() { setBusy(true); try { await submit({ assignmentId: selectedItem.assignmentId as never, scores: sorted.map((c: any) => ({ criterionId: c._id as never, score: scores[c._id] ?? selectedItem.scoredCriteria.find((s: any) => s.criterionId === c._id)?.score ?? c.minScore })), privateNotes: notes }); toast.success("Scores submitted"); } catch (e: any) { toast.error(e.message); } finally { setBusy(false); } }
  return <div className="container max-w-3xl py-10"><Link to="/judge" className="font-mono text-xs uppercase text-primary">← Back to queue</Link><header className="mb-8 mt-5"><div className="mono-label mb-1">score project</div><h1 className="text-3xl font-bold">{item.submission.title}</h1><p className="mt-2 text-sm text-muted-foreground">Team: {item.submission.teamName}</p></header><div className="mb-6 rounded-xl border border-border bg-card p-6"><p className="whitespace-pre-wrap text-sm leading-relaxed text-muted-foreground">{item.submission.description}</p></div><section className="grid gap-5 rounded-xl border border-border bg-card p-6">{sorted.map((c: any) => { const current = scores[c._id] ?? item.scoredCriteria.find((s: any) => s.criterionId === c._id)?.score ?? Math.ceil((c.minScore + c.maxScore) / 2); return <label key={c._id} className="grid gap-2"><span className="flex justify-between text-sm font-medium"><span>{c.name} <span className="font-mono text-xs text-primary">{Math.round(c.weight * 100)}%</span></span><span className="font-mono text-primary">{current}/{c.maxScore}</span></span><input type="range" min={c.minScore} max={c.maxScore} step={0.5} value={current} disabled={item.locked} onChange={e => setScores({ ...scores, [c._id]: Number(e.target.value) })} className="w-full accent-[hsl(var(--primary))]" /><span className="text-xs text-muted-foreground">{c.description}</span></label>; })}<label className="grid gap-1"><span className="mono-label">Private notes</span><textarea rows={4} value={notes} onChange={e => setNotes(e.target.value)} className="rounded-md border border-input bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring" placeholder="Your private observations…" /></label><button disabled={busy || item.locked || !allScored} onClick={save} className="min-h-11 w-full rounded-lg bg-primary px-5 font-mono text-xs font-semibold uppercase text-primary-foreground disabled:opacity-40">{busy ? "Saving…" : item.status === "completed" ? "Update scores" : "Submit score"}</button></section></div>;
}
