import { useMemo, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api } from "@/convex/_generated/api";
import { toast } from "sonner";

const statusClass = (s:string) => s === "draft" ? "bg-muted text-muted-foreground" : "bg-success/10 text-success";
export function OrganizerEvents() {
  const events = useQuery(api.events.listMine, {}); const [status,setStatus] = useState("all");
  const filtered = useMemo(()=> (events ?? []).filter((e:any)=>status === "all" || e.status === status), [events,status]);
  return <div className="container max-w-7xl py-8"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div className="mono-label mb-1">organizer / events</div><h1 className="text-3xl font-bold">Your events</h1></div><Link to="/organizer/events/new" className="rounded-lg bg-primary px-4 py-2.5 font-mono text-xs font-semibold uppercase text-primary-foreground">Create Event</Link></div><div className="mb-4 flex gap-2"><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border border-input bg-background px-3 py-2 text-sm"><option value="all">All statuses</option><option value="draft">Draft</option><option value="registration">Open</option><option value="published">Published</option><option value="archived">Archived</option></select></div><div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="w-full text-left text-sm"><thead className="border-b border-border font-mono text-[11px] uppercase text-muted-foreground"><tr><th className="p-4">Title</th><th className="p-4">Status</th><th className="p-4">Participants</th><th className="p-4">Submissions</th><th className="p-4">Dates</th></tr></thead><tbody>{filtered.map((e:any)=><tr key={e._id} onClick={()=>location.assign(`/organizer/events/${e.slug}`)} className="cursor-pointer border-b border-border/50 last:border-0 hover:bg-secondary/40"><td className="p-4"><div className="font-semibold">{e.title}</div><div className="font-mono text-xs text-muted-foreground">/{e.slug}</div></td><td className="p-4"><span className={`rounded-full px-2.5 py-1 font-mono text-[10px] uppercase ${statusClass(e.status)}`}>{e.status}</span></td><td className="p-4 text-muted-foreground">—</td><td className="p-4 text-muted-foreground">—</td><td className="p-4 font-mono text-xs text-muted-foreground">deadline {new Date(e.submissionDeadline).toLocaleDateString()}</td></tr>)}</tbody></table>{filtered.length === 0 && <div className="p-12 text-center font-mono text-sm text-muted-foreground">No events yet. Create your first event.</div>}</div></div>;
}
export function OrganizerEventManagement() {
 const {slug}=useParams(); const navigate=useNavigate(); const event=useQuery(api.events.getBySlug,slug?{slug}:"skip"); const publish=useMutation(api.events.publish); const unpublish=useMutation(api.events.unpublish); const tracks=useQuery(api.tracks.listByEvent,event?{eventId:event._id}:"skip"); const [tab,setTab]=useState("Overview");
 if(!event)return <div className="container py-24 text-center font-mono text-muted-foreground">loading…</div>;
 const tabs=["Overview","Tracks & Prizes","Rules & FAQ","Participants","Teams","Submissions","Judges","Judging","Results","Audit"];
 return <div className="container max-w-7xl py-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="mono-label mb-1">event management</div><h1 className="text-3xl font-bold">{event.title}</h1><div className="mt-2 flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 font-mono text-[10px] uppercase ${statusClass(event.status)}`}>{event.status}</span><span className="font-mono text-xs text-muted-foreground">/{event.slug}</span></div></div><div className="flex gap-2"><Link to={`/organizer/events/${event.slug}/edit`} className="rounded-lg border border-border px-4 py-2 font-mono text-xs uppercase">Edit</Link><button onClick={async()=>{try{if(event.status === "draft"){await publish({eventId:event._id});toast.success("Event published")}else{await unpublish({eventId:event._id});toast.success("Event unpublished")}}catch(e:any){toast.error(e.message)}}} className="rounded-lg bg-primary px-4 py-2 font-mono text-xs uppercase text-primary-foreground">{event.status === "draft" ? "Publish" : "Unpublish"}</button></div></div><div className="mb-6 flex gap-1 overflow-x-auto border-b border-border pb-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap rounded-lg px-3 py-2 font-mono text-xs uppercase ${tab===t?"bg-primary text-primary-foreground":"text-muted-foreground hover:bg-secondary"}`}>{t}</button>)}</div>{tab === "Overview" ? <Overview event={event}/> : tab === "Tracks & Prizes" ? <Tracks eventId={event._id} tracks={tracks ?? []}/> : tab === "Rules & FAQ" ? <div className="rounded-xl border border-border bg-card p-6"><h2 className="mb-3 text-xl font-semibold">Rules & FAQ</h2><pre className="whitespace-pre-wrap text-sm text-muted-foreground">{event.rules || "No rules have been added yet."}</pre></div> : <div className="rounded-xl border border-dashed border-border bg-card/50 p-16 text-center"><h2 className="text-xl font-semibold">{tab}</h2><p className="mt-2 font-mono text-sm text-muted-foreground">Coming soon — planned for the next platform pass.</p></div>}</div>;
}
function Overview({event}:any){return <div className="grid gap-4 sm:grid-cols-4">{[["Status",event.status],["Team size",`${event.minTeamSize ?? 1}–${event.maxTeamSize ?? 4}`],["Registration closes",new Date(event.registrationCloses ?? event.registrationEnd).toLocaleString()],["Submission deadline",new Date(event.submissionDeadline).toLocaleString()]].map(([l,v])=><div key={l} className="rounded-xl border border-border bg-card p-5"><div className="font-mono text-lg font-bold text-primary">{v}</div><div className="mono-label mt-1">{l}</div></div>)}</div>}
function Tracks({eventId,tracks}:any){const create=useMutation(api.tracks.create);const remove=useMutation(api.tracks.remove);const [name,setName]=useState("");const [prize,setPrize]=useState("");return <div className="grid gap-4"><div className="rounded-xl border border-border bg-card p-6"><h2 className="mb-3 text-xl font-semibold">Tracks & prizes</h2><div className="flex flex-wrap gap-2"><input className="rounded-lg border border-input bg-background px-3 py-2 text-sm" placeholder="Track name" value={name} onChange={e=>setName(e.target.value)}/><input className="rounded-lg border border-input bg-background px-3 py-2 text-sm" placeholder="Prize description" value={prize} onChange={e=>setPrize(e.target.value)}/><button onClick={async()=>{if(!name)return;await create({eventId,name,description:"",prizeDescription:prize,prizeAmount:0});setName("");setPrize("")}} className="rounded-lg bg-primary px-4 py-2 font-mono text-xs uppercase text-primary-foreground">Add track</button></div></div>{tracks.map((t:any)=><div key={t._id} className="flex items-center justify-between rounded-xl border border-border bg-card p-5"><div><div className="font-semibold">{t.name}</div><div className="text-sm text-muted-foreground">{t.prizeDescription || "No prize details"}</div></div><button onClick={()=>remove({trackId:t._id})} className="font-mono text-xs uppercase text-destructive">Delete</button></div>)}</div>}
