import { Link } from "react-router-dom";
import { ArrowRight, LoaderCircle } from "lucide-react";

export const dateLabel = (value?: number) => value ? new Date(value).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}) : "—";
export const stageLabel = (value?: string) => (value ?? "draft").replaceAll("_"," ");
export function Loading(){ return <div className="mx-auto flex min-h-[55vh] max-w-7xl items-center justify-center"><div className="glass flex items-center gap-3 rounded-3xl px-6 py-4 text-sm text-muted-foreground"><LoaderCircle size={16} className="animate-spin"/> Loading workspace</div></div>; }
export function Section({eyebrow,title,children,action}:{eyebrow?:string;title:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div>{eyebrow&&<div className="eyebrow mb-2">{eyebrow}</div>}<h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{title}</h1></div>{action}</div>{children}</section>;}
export function Empty({title,body,href,label}:{title:string;body:string;href?:string;label?:string}){return <div className="glass rounded-[2rem] p-10 text-center"><h2 className="text-xl font-bold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">{body}</p>{href&&<Link to={href} className="glass-button mt-6">{label??"Continue"}<ArrowRight size={15}/></Link>}</div>;}
export function Stat({label,value}:{label:string;value:React.ReactNode}){return <div className="glass rounded-3xl p-5"><div className="text-2xl font-bold">{value}</div><div className="mt-2 text-sm text-muted-foreground">{label}</div></div>;}
export function EventCard({event}:{event:any}){return <Link to={`/e/${event.slug}`} className="glass group overflow-hidden rounded-[1.75rem] transition hover:-translate-y-1"><div className="relative h-36 bg-white/30 dark:bg-white/[.06]">{event.bannerUrl&&<img src={event.bannerUrl} alt="" className="h-full w-full object-cover opacity-50 transition duration-500 group-hover:scale-105"/>}<div className="absolute inset-0 bg-gradient-to-t from-black/25 to-transparent"/><span className="absolute bottom-4 left-4 rounded-full border border-white/50 bg-white/25 px-3 py-1 text-xs font-semibold text-white backdrop-blur-xl">{stageLabel(event.status)}</span></div><div className="p-5"><h2 className="line-clamp-1 text-lg font-bold">{event.title}</h2><p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{event.shortDescription||event.tagline}</p><div className="mt-5 flex justify-between text-xs text-muted-foreground"><span>{event.participantCount??0} participants</span><span>Due {dateLabel(event.submissionDeadline)}</span></div></div></Link>;}
